[package]
name = "garf"
version = "0.1.0"
edition = "2024"

[dependencies]
poise = "0.6.1"
tokio = { version = "1.43.0", features = ["full"] }
mini-redis = "0.4"
dotenv = "0.15.0"
tabled = "0.18.0"
sqlx = { version = "0.7", features = ["sqlite", "runtime-tokio-native-tls"] }
